image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar -P:profile=test &


build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true